SQL> SELECT dbms_metadata.get_ddl('TABLE', table_name) FROM user_tables;
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."CLIENTE"                                                                                                                                                                 
   (	"ID_CLIENTE" NUMBER(*,0),                                                                                                                                                                          
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE,                                                                                                                                                                
	"TELEFONO" VARCHAR2(15),                                                                                                                                                                               
	"DIRECCION" VARCHAR2(100),                                                                                                                                                                             
	"PEDIDO" VARCHAR2(100),                                                                                                                                                                                
	"SATISFACCION" VARCHAR2(100),                                                                                                                                                                          
	 PRIMARY KEY ("ID_CLIENTE")                                                                                                                                                                            
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645                                                                                                                                 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1                                                                                                                                                           
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)                                                                                                                                     
  TABLESPACE "USERS"  ENABLE                                                                                                                                                                            
   ) SEGMENT CREATION IMMEDIATE                                                                                                                                                                         
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645                                                                                                                                 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1                                                                                                                                                           
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."PROVEEDOR"                                                                                                                                                               
   (	"ID_PROVEEDOR" NUMBER(*,0),                                                                                                                                                                        
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE,                                                                                                                                                                
	"TIPO_PRODUCTO" VARCHAR2(50),                                                                                                                                                                          
	"URL_FICHA_PRODUCTO" VARCHAR2(100),                                                                                                                                                                    
	 PRIMARY KEY ("ID_PROVEEDOR")                                                                                                                                                                          
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  TABLESPACE "USERS"  ENABLE                                                                                                                                                                            
   ) SEGMENT CREATION DEFERRED                                                                                                                                                                          
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."OPERARIO"                                                                                                                                                                
   (	"ID_OPERARIO" NUMBER(*,0),                                                                                                                                                                         
	"NOMBRE" VARCHAR2(50) NOT NULL ENABLE,                                                                                                                                                                 
	"TURNO_TRABAJO" VARCHAR2(20),                                                                                                                                                                          
	 PRIMARY KEY ("ID_OPERARIO")                                                                                                                                                                           
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645                                                                                                                                 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1                                                                                                                                                           
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)                                                                                                                                     
  TABLESPACE "USERS"  ENABLE                                                                                                                                                                            
   ) SEGMENT CREATION IMMEDIATE                                                                                                                                                                         
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645                                                                                                                                 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1                                                                                                                                                           
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."FRANQUICIADO"                                                                                                                                                            
   (	"ID_FRANQUICIADO" NUMBER(*,0),                                                                                                                                                                     
	"UBICACION" VARCHAR2(100),                                                                                                                                                                             
	 PRIMARY KEY ("ID_FRANQUICIADO")                                                                                                                                                                       
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  TABLESPACE "USERS"  ENABLE                                                                                                                                                                            
   ) SEGMENT CREATION DEFERRED                                                                                                                                                                          
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."CAMARA"                                                                                                                                                                  
   (	"ID_CAMARA" NUMBER(*,0),                                                                                                                                                                           
	"PORCENTAJE_USO" NUMBER(10,2),                                                                                                                                                                         
	 PRIMARY KEY ("ID_CAMARA")                                                                                                                                                                             
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  TABLESPACE "USERS"  ENABLE                                                                                                                                                                            
   ) SEGMENT CREATION DEFERRED                                                                                                                                                                          
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."LOTE_ALIMENTO"                                                                                                                                                           
   (	"ID_LOTE_ALIMENTO" NUMBER(*,0),                                                                                                                                                                    
	"DESCRIPCION" CLOB,                                                                                                                                                                                    
	"FECHA_LLEGADA" DATE,                                                                                                                                                                                  
	"FECHA_CADUCIDAD" DATE,                                                                                                                                                                                
	"CANTIDAD" NUMBER(10,2),                                                                                                                                                                               
	 PRIMARY KEY ("ID_LOTE_ALIMENTO")                                                                                                                                                                      
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  TABLESPACE "USERS"  ENABLE                                                                                                                                                                            
   ) SEGMENT CREATION DEFERRED                                                                                                                                                                          
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
 LOB ("DESCRIPCION") STORE AS SECUREFILE (                                                                                                                                                              
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192                                                                                                                                              
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."REGISTRO"                                                                                                                                                                
   (	"ID_REGISTRO" NUMBER(*,0),                                                                                                                                                                         
	"ID_CAMARA" NUMBER(*,0),                                                                                                                                                                               
	"TIPO_REGISTRO" VARCHAR2(50),                                                                                                                                                                          
	"TIMESTAMP_REGISTRO" TIMESTAMP (6),                                                                                                                                                                    
	"HUMEDAD" NUMBER(5,2),                                                                                                                                                                                 
	"CO2" NUMBER(5,2),                                                                                                                                                                                     
	"TEMPERATURA" NUMBER(5,2),                                                                                                                                                                             
	 PRIMARY KEY ("ID_REGISTRO")                                                                                                                                                                           
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  TABLESPACE "USERS"  ENABLE,                                                                                                                                                                           
	 FOREIGN KEY ("ID_CAMARA")                                                                                                                                                                             
	  REFERENCES "INSECTMARCOS"."CAMARA" ("ID_CAMARA") ENABLE                                                                                                                                              
   ) SEGMENT CREATION DEFERRED                                                                                                                                                                          
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."SENSORES"                                                                                                                                                                
   (	"ID_SENSOR" NUMBER(*,0),                                                                                                                                                                           
	"ID_REGISTRO" NUMBER(*,0),                                                                                                                                                                             
	"TIPO_SENSOR" VARCHAR2(50),                                                                                                                                                                            
	"UBICACION" VARCHAR2(50),                                                                                                                                                                              
	 PRIMARY KEY ("ID_SENSOR")                                                                                                                                                                             
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  TABLESPACE "USERS"  ENABLE,                                                                                                                                                                           
	 FOREIGN KEY ("ID_REGISTRO")                                                                                                                                                                           
	  REFERENCES "INSECTMARCOS"."REGISTRO" ("ID_REGISTRO") ENABLE                                                                                                                                          
   ) SEGMENT CREATION DEFERRED                                                                                                                                                                          
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."ENGORDE"                                                                                                                                                                 
   (	"ID_PALLET" NUMBER(*,0),                                                                                                                                                                           
	"ID_CAMARA" NUMBER(*,0),                                                                                                                                                                               
	"ID_OPERARIO" NUMBER(*,0),                                                                                                                                                                             
	"ID_LOTE_MADRE" NUMBER(*,0),                                                                                                                                                                           
	"PASILLO" NUMBER(*,0),                                                                                                                                                                                 
	"POSICION" VARCHAR2(50),                                                                                                                                                                               
	"TIMESTAMP_UBICACION" TIMESTAMP (6),                                                                                                                                                                   
	"FECHA_MONTAJE" DATE NOT NULL ENABLE,                                                                                                                                                                  
	"FECHA_DESMONTAJE" DATE NOT NULL ENABLE,                                                                                                                                                               
	"FECHA_DESMONTAJE_PREVISTA" DATE NOT NULL ENABLE,                                                                                                                                                      
	"DESTINO" VARCHAR2(20),                                                                                                                                                                                
	 PRIMARY KEY ("ID_PALLET")                                                                                                                                                                             
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  TABLESPACE "USERS"  ENABLE,                                                                                                                                                                           
	 FOREIGN KEY ("ID_CAMARA")                                                                                                                                                                             
	  REFERENCES "INSECTMARCOS"."CAMARA" ("ID_CAMARA") ENABLE,                                                                                                                                             
	 FOREIGN KEY ("ID_OPERARIO")                                                                                                                                                                           
	  REFERENCES "INSECTMARCOS"."OPERARIO" ("ID_OPERARIO") ENABLE                                                                                                                                          
   ) SEGMENT CREATION DEFERRED                                                                                                                                                                          
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."VOLADERO"                                                                                                                                                                
   (	"ID_VOLADERO" NUMBER(*,0),                                                                                                                                                                         
	"ID_PALLET" NUMBER(*,0),                                                                                                                                                                               
	"FECHA_INICIO" DATE NOT NULL ENABLE,                                                                                                                                                                   
	"FECHA_FIN" DATE NOT NULL ENABLE,                                                                                                                                                                      
	"FECHA_FIN_ESTIMADA" DATE NOT NULL ENABLE,                                                                                                                                                             
	 PRIMARY KEY ("ID_VOLADERO")                                                                                                                                                                           
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  TABLESPACE "USERS"  ENABLE,                                                                                                                                                                           
	 FOREIGN KEY ("ID_PALLET")                                                                                                                                                                             
	  REFERENCES "INSECTMARCOS"."ENGORDE" ("ID_PALLET") ENABLE                                                                                                                                             
   ) SEGMENT CREATION DEFERRED                                                                                                                                                                          
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."INCUBACION"                                                                                                                                                              
   (	"ID_LOTE_MADRE" NUMBER(*,0),                                                                                                                                                                       
	"ID_LOTE_ALIMENTO" NUMBER(*,0),                                                                                                                                                                        
	"ID_OPERARIO" NUMBER(*,0),                                                                                                                                                                             
	"ID_VOLADERO" NUMBER(*,0),                                                                                                                                                                             
	"FECHA_INICIO" DATE NOT NULL ENABLE,                                                                                                                                                                   
	"FECHA_FIN" DATE NOT NULL ENABLE,                                                                                                                                                                      
	"ORIGEN" VARCHAR2(20),                                                                                                                                                                                 
	"GRAMOS_HUEVOS" NUMBER(10,2),                                                                                                                                                                          
	"N_BANDEJAS" NUMBER(*,0),                                                                                                                                                                              
	 PRIMARY KEY ("ID_LOTE_MADRE")                                                                                                                                                                         
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  TABLESPACE "USERS"  ENABLE,                                                                                                                                                                           
	 FOREIGN KEY ("ID_LOTE_ALIMENTO")                                                                                                                                                                      
	  REFERENCES "INSECTMARCOS"."LOTE_ALIMENTO" ("ID_LOTE_ALIMENTO") ENABLE,                                                                                                                               
	 FOREIGN KEY ("ID_OPERARIO")                                                                                                                                                                           
	  REFERENCES "INSECTMARCOS"."OPERARIO" ("ID_OPERARIO") ENABLE                                                                                                                                          
   ) SEGMENT CREATION DEFERRED                                                                                                                                                                          
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."PRODUCTOS"                                                                                                                                                               
   (	"ID_BIGBAG" NUMBER(*,0),                                                                                                                                                                           
	"ID_LOTE_MADRE" NUMBER(*,0),                                                                                                                                                                           
	"ID_PALLET" NUMBER(*,0),                                                                                                                                                                               
	"ID_OPERARIO" NUMBER(*,0),                                                                                                                                                                             
	"ID_PEDIDO" NUMBER(*,0),                                                                                                                                                                               
	"FECHA_PRODUCCION" DATE NOT NULL ENABLE,                                                                                                                                                               
	"FECHA_CADUCIDAD" DATE NOT NULL ENABLE,                                                                                                                                                                
	"URL_PDF" VARCHAR2(100),                                                                                                                                                                               
	"TIPO_PRODUCTO" VARCHAR2(50),                                                                                                                                                                          
	"UBICACION_ALMACEN" VARCHAR2(50),                                                                                                                                                                      
	 PRIMARY KEY ("ID_BIGBAG")                                                                                                                                                                             
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  TABLESPACE "USERS"  ENABLE,                                                                                                                                                                           
	 FOREIGN KEY ("ID_LOTE_MADRE")                                                                                                                                                                         
	  REFERENCES "INSECTMARCOS"."INCUBACION" ("ID_LOTE_MADRE") ENABLE,                                                                                                                                     
	 FOREIGN KEY ("ID_PALLET")                                                                                                                                                                             
	  REFERENCES "INSECTMARCOS"."ENGORDE" ("ID_PALLET") ENABLE,                                                                                                                                            
	 FOREIGN KEY ("ID_OPERARIO")                                                                                                                                                                           
	  REFERENCES "INSECTMARCOS"."OPERARIO" ("ID_OPERARIO") ENABLE,                                                                                                                                         
	 FOREIGN KEY ("ID_PEDIDO")                                                                                                                                                                             
	  REFERENCES "INSECTMARCOS"."TAREA" ("ID_TAREA") ENABLE                                                                                                                                                
   ) SEGMENT CREATION DEFERRED                                                                                                                                                                          
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."TAREA"                                                                                                                                                                   
   (	"ID_TAREA" NUMBER(*,0),                                                                                                                                                                            
	"ID_CLIENTE" NUMBER(*,0),                                                                                                                                                                              
	"ESTADO" VARCHAR2(20) NOT NULL ENABLE,                                                                                                                                                                 
	"TIPO_TAREA" VARCHAR2(50) NOT NULL ENABLE,                                                                                                                                                             
	"FECHA_ENTREGA" VARCHAR2(20),                                                                                                                                                                          
	"FECHA_PREVISTA" DATE NOT NULL ENABLE,                                                                                                                                                                 
	"LOGISTICA" VARCHAR2(20),                                                                                                                                                                              
	"ID_OPERARIO" NUMBER,                                                                                                                                                                                  
	"DESCRIPCION" VARCHAR2(255),                                                                                                                                                                           
	"FECHA_CREACION" DATE,                                                                                                                                                                                 
	 PRIMARY KEY ("ID_TAREA")                                                                                                                                                                              
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645                                                                                                                                 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1                                                                                                                                                           
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)                                                                                                                                     
  TABLESPACE "USERS"  ENABLE,                                                                                                                                                                           
	 FOREIGN KEY ("ID_CLIENTE")                                                                                                                                                                            
	  REFERENCES "INSECTMARCOS"."CLIENTE" ("ID_CLIENTE") ENABLE                                                                                                                                            
   ) SEGMENT CREATION IMMEDIATE                                                                                                                                                                         
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645                                                                                                                                 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1                                                                                                                                                           
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."PEDIDO"                                                                                                                                                                  
   (	"ID_PEDIDO" NUMBER(*,0),                                                                                                                                                                           
	"ID_CLIENTE" NUMBER(*,0),                                                                                                                                                                              
	"ESTADO" VARCHAR2(20) NOT NULL ENABLE,                                                                                                                                                                 
	"TIPO_PRODUCTO" VARCHAR2(50) NOT NULL ENABLE,                                                                                                                                                          
	"CANTIDAD" NUMBER(10,2),                                                                                                                                                                               
	"FECHA_ENTREGA" DATE NOT NULL ENABLE,                                                                                                                                                                  
	"FECHA_PREVISTA" DATE NOT NULL ENABLE,                                                                                                                                                                 
	"LOGISTICA" VARCHAR2(20),                                                                                                                                                                              
	 PRIMARY KEY ("ID_PEDIDO")                                                                                                                                                                             
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645                                                                                                                                 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1                                                                                                                                                           
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)                                                                                                                                     
  TABLESPACE "USERS"  ENABLE,                                                                                                                                                                           
	 FOREIGN KEY ("ID_CLIENTE")                                                                                                                                                                            
	  REFERENCES "INSECTMARCOS"."CLIENTE" ("ID_CLIENTE") ENABLE                                                                                                                                            
   ) SEGMENT CREATION IMMEDIATE                                                                                                                                                                         
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645                                                                                                                                 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1                                                                                                                                                           
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."EVENTO"                                                                                                                                                                  
   (	"ID_EVENTO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 999                                                                                                                        
9999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE                                                                                                                         
 NOKEEP  NOSCALE  NOT NULL ENABLE,                                                                                                                                                                      
	"TIPO_EVENTO" VARCHAR2(50) NOT NULL ENABLE,                                                                                                                                                            
	"DESCRIPCION" VARCHAR2(255),                                                                                                                                                                           
	"FECHA_INICIO" DATE NOT NULL ENABLE,                                                                                                                                                                   
	"FECHA_FIN" DATE,                                                                                                                                                                                      
	"ESTADO" VARCHAR2(50),                                                                                                                                                                                 
	"ID_OPERARIO" NUMBER,                                                                                                                                                                                  
	"TITULO" VARCHAR2(100),                                                                                                                                                                                
	"ID_TAREA" NUMBER,                                                                                                                                                                                     
	 PRIMARY KEY ("ID_EVENTO")                                                                                                                                                                             
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645                                                                                                                                 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1                                                                                                                                                           
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)                                                                                                                                     
  TABLESPACE "USERS"  ENABLE,                                                                                                                                                                           
	 CONSTRAINT "FK_EVENTO_OPERARIO" FOREIGN KEY ("ID_OPERARIO")                                                                                                                                           
	  REFERENCES "INSECTMARCOS"."OPERARIO" ("ID_OPERARIO") ENABLE,                                                                                                                                         
	 CONSTRAINT "FK_EVENTO_TAREA" FOREIGN KEY ("ID_TAREA")                                                                                                                                                 
	  REFERENCES "INSECTMARCOS"."TAREA" ("ID_TAREA") ON DELETE SET NULL ENABLE                                                                                                                             
   ) SEGMENT CREATION IMMEDIATE                                                                                                                                                                         
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645                                                                                                                                 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1                                                                                                                                                           
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
  CREATE TABLE "INSECTMARCOS"."USUARIOS"                                                                                                                                                                
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999                                                                                                                        
999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP                                                                                                                        
  NOSCALE  NOT NULL ENABLE,                                                                                                                                                                             
	"EMAIL" VARCHAR2(255) NOT NULL ENABLE,                                                                                                                                                                 
	"USERNAME" VARCHAR2(100) NOT NULL ENABLE,                                                                                                                                                              
	"PASSWORD_HASH" VARCHAR2(255) NOT NULL ENABLE,                                                                                                                                                         
	"ROL" VARCHAR2(20) DEFAULT 'user',                                                                                                                                                                     
	"CREATED_AT" DATE DEFAULT SYSDATE,                                                                                                                                                                     
	"ID_OPERARIO" NUMBER,                                                                                                                                                                                  
	 PRIMARY KEY ("ID")                                                                                                                                                                                    
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645                                                                                                                                 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1                                                                                                                                                           
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)                                                                                                                                     
  TABLESPACE "USERS"  ENABLE,                                                                                                                                                                           
	 UNIQUE ("EMAIL")                                                                                                                                                                                      
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS                                                                                                                                     
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645                                                                                                                                 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1                                                                                                                                                           
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)                                                                                                                                     
  TABLESPACE "USERS"  ENABLE,                                                                                                                                                                           
	 CONSTRAINT "FK_OPERARIO" FOREIGN KEY ("ID_OPERARIO")                                                                                                                                                  
	  REFERENCES "INSECTMARCOS"."OPERARIO" ("ID_OPERARIO") ENABLE                                                                                                                                          
   ) SEGMENT CREATION IMMEDIATE                                                                                                                                                                         
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255                                                                                                                                                         
 NOCOMPRESS LOGGING                                                                                                                                                                                     
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645                                                                                                                                 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1                                                                                                                                                           
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)                                                                                                                                     
  TABLESPACE "USERS"                                                                                                                                                                                    
                                                                                                                                                                                                        
SQL> SPOOL OFF
